#!/bin/bash

if [ -z $PICTION_BRIDGE_HOME ]; then
    echo "Environment variable PICTION_BRIDGE_HOME must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_CONF ]; then
    echo "Environment variable PICTION_BRIDGE_CONF must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_USER ]; then
    echo "Environment variable PICTION_BRIDGE_DB_USER must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_PW ]; then
    echo "Environment variable PICTION_BRIDGE_DB_PW must be set"
    exit 1
fi

CLASSPATH=$PICTION_BRIDGE_HOME/lib/${project.build.finalName}.${project.packaging}:$PICTION_BRIDGE_HOME/lib/*
CONF_FILE=$PICTION_BRIDGE_HOME/conf/$PICTION_BRIDGE_CONF.xml
LOG4J_CONF_FILE=$PICTION_BRIDGE_HOME/conf/log4j2.xml
MAIN_CLASS=edu.berkeley.cspace.pictionbridge.PictionBridge

java -classpath $CLASSPATH -Dlog4j.configurationFile=$LOG4J_CONF_FILE -DpictionBridge.configurationFile=$CONF_FILE -DpictionBridge.home=$PICTION_BRIDGE_HOME $MAIN_CLASS