#!/bin/bash

# If none of the required environment variables are set, try sourcing a resource file in the user's home directory.

RESOURCE_FILE=~/.pictionbridge

if [[ (-z $PICTION_BRIDGE_HOME) && 
      (-z $PICTION_BRIDGE_CONF) &&
      (-z $PICTION_BRIDGE_DB_HOST) &&
      (-z $PICTION_BRIDGE_DB_PORT) &&
      (-z $PICTION_BRIDGE_DB_NAME) &&
      (-z $PICTION_BRIDGE_DB_USER) &&
      (-z $PICTION_BRIDGE_DB_PW) &&
      (-z $PICTION_BRIDGE_CSPACE_HOST) && 
      (-z $PICTION_BRIDGE_CSPACE_USER) && 
      (-z $PICTION_BRIDGE_CSPACE_PW) ]]; then
    
    if [ -f $RESOURCE_FILE ]; then
        . $RESOURCE_FILE 
    fi
fi

# Ensure the required environment variables are set.

if [ -z $PICTION_BRIDGE_HOME ]; then
    echo "Environment variable PICTION_BRIDGE_HOME must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_CONF ]; then
    echo "Environment variable PICTION_BRIDGE_CONF must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_HOST ]; then
    echo "Environment variable PICTION_BRIDGE_DB_HOST must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_PORT ]; then
    echo "Environment variable PICTION_BRIDGE_DB_PORT must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_NAME ]; then
    echo "Environment variable PICTION_BRIDGE_DB_NAME must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_USER ]; then
    echo "Environment variable PICTION_BRIDGE_DB_USER must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_DB_PW ]; then
    echo "Environment variable PICTION_BRIDGE_DB_PW must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_CSPACE_HOST ]; then
    echo "Environment variable PICTION_BRIDGE_CSPACE_HOST must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_CSPACE_USER ]; then
    echo "Environment variable PICTION_BRIDGE_CSPACE_USER must be set"
    exit 1
fi

if [ -z $PICTION_BRIDGE_CSPACE_PW ]; then
    echo "Environment variable PICTION_BRIDGE_CSPACE_PW must be set"
    exit 1
fi

# Execute the java program.

CLASSPATH=$PICTION_BRIDGE_HOME/lib/pictionbridge-1.0-beta.jar:$PICTION_BRIDGE_HOME/lib/*
CONF_FILE=$PICTION_BRIDGE_HOME/conf/$PICTION_BRIDGE_CONF.xml
LOG4J_CONF_FILE=$PICTION_BRIDGE_HOME/conf/log4j2.xml
MAIN_CLASS=edu.berkeley.cspace.pictionbridge.PictionBridge

java -classpath $CLASSPATH -Dlog4j.configurationFile=$LOG4J_CONF_FILE -DpictionBridge.configurationFile=$CONF_FILE -DpictionBridge.home=$PICTION_BRIDGE_HOME $MAIN_CLASS
